### PR TITLE
fix consistent clearing of internal cache entries during shutdown

### LINKED ISSUE #92: When the ignite node exits the cluster,  the event bus message sending fails.
Version
3.9.x plus latest releases
Ignite 2.7.0

Context
When the ignite node exits the cluster, the event bus message sending fails.

Code
package io.vertx.core.spi.cluster.impl.selector;

import io.vertx.core.Promise;
import io.vertx.core.eventbus.Message;
import io.vertx.core.spi.cluster.ClusterManager;
import io.vertx.core.spi.cluster.RegistrationInfo;

import java.util.Collections;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;
import java.util.function.BiConsumer;

import static java.util.stream.Collectors.toList;

/**
 * @author Thomas Segismont
 */
public class Selectors {

  private final ConcurrentMap<String, SelectorEntry> map = new ConcurrentHashMap<>(0);
  private final ClusterManager clusterManager;

the map caches node information, so when the ignote node exits the cluster, the map cache should be cleared.

### PR DESCRIPTION
**Pull request by zyclonite**
should fix #92 and #94

### CODE REVIEW

File: src/main/java/io/vertx/spi/cluster/ignite/IgniteClusterManager.java [hunk 1]
```diff
@@ -279,44 +280,56 @@ public void join(Promise<Void> promise) {
...
-                    break;
-                }
+                  }
+                  log.info("node " + id + " left the cluster");
+                  break;
+                case EVT_NODE_SEGMENTED:
+                  if(customIgnite) {
+                    log.info("node got segmented");
+                  } else {
+                    log.warn("node got segmented and will be shut down");
```
Comment (tsegismont) [inline src/main/java/io/vertx/spi/cluster/ignite/IgniteClusterManager.java:320]: If segmentation is an unrecoverable situation, then the message should be a warning in both cases, and we should fail the promise `f`.

The user has to decide how to close instead of us shutting down everything from here

Comment (zyclonite) [reply src/main/java/io/vertx/spi/cluster/ignite/IgniteClusterManager.java:320]: yes, makes sense

just to explain my initial thought:
in the custom ignite case the user needs to decide already what happens in that situation (which stops the cache by default or could trigger a jvm restart) when configuring the instance - when this segmentation happens, it's already too late in most cases

**Review by tsegismont — APPROVED** [review]
@zyclonite it looks good to me except I would not close the Vert.x instance in the cluster manager. The user might need to run some tasks in attempt to save some data before closing (e.g. with Vert.x FileSystem or HTTP Client API)

**Comment by zyclonite** [comment]
@tsegismont i honestly do not like the vertx.close() either... but isn't that triggering a graceful shutdown and stopping of all verticles anyway?

the reason for doing the `stop` is, that ignite stops the member node and so all tries to access the cache will fail from that point on (so there seems to be no reason to keep anything alive)
this happens only on split-brain situations or when all the configured timeouts are passed (depends as well on the base topology)

**Comment by tsegismont** [comment]
@zyclonite I understand the logic behind this line. But I fear this would cause more problems than it solves.

Perhaps this could be made configurable?

**Comment by zyclonite** [comment]
@tsegismont sure i can do that

**Comment by zyclonite** [comment]
@tsegismont from my perspective this can be merged

**Review by tsegismont — APPROVED** [review]
Thank you @zyclonite !
